#ifndef CMANAGER_INVENTURVERWALTUNG_H
#define CMANAGER_INVENTURVERWALTUNG_H

#include <QSqlDatabase>


class cMANAGER_INVENTURVERWALTUNG
{
public:
    cMANAGER_INVENTURVERWALTUNG();
    ~cMANAGER_INVENTURVERWALTUNG();
protected:
    QSqlDatabase m_db;
};

#endif // CMANAGER_INVENTURVERWALTUNG_H
