

select * from ABTEILUNG_ABT
select * from STANDORT
select * from GEGENSTAENDE
select * from GEGENSTAENDE_HIST
select * from PERSONEN
select * from BEREICH
select * from GRUPPE
select * from ZUSTAND


USE datenbank
GO

/****** Object:  Table [dbo].[ZUSTAND]    Script Date: 05.12.2025 13:18:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ZUSTAND](
	[ZUSTAND_ID] [int] NOT NULL,
	[BESCHREIBUNG] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ZUSTAND_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE datenbank
GO

/****** Object:  Table [dbo].[STANDORT]    Script Date: 05.12.2025 13:19:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STANDORT](
	[STANDORT_ID] [int] NOT NULL,
	[BESCHREIBUNG] [varchar](255) NULL,
	[BUNDESLAND] [varchar](255) NULL,
	[PLZ] [float] NULL,
	[STRASSE] [varchar](255) NULL,
	[HAUS_NR] [int] NULL,
	[ORT] [varchar](255) NULL,
	[HAUSZUSATZ] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[STANDORT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE datenbank
GO

/****** Object:  Table [dbo].[PERSONEN]    Script Date: 05.12.2025 13:20:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERSONEN](
	[PERSONEN_ID] [int] NOT NULL,
	[NAME] [varchar](255) NULL,
	[VORNAME] [varchar](255) NULL,
	[BENUTZERNAME] [varchar](255) NULL,
	[PASSWORT] [varchar](255) NULL,
	[BEREICH_ID] [int] NULL,
	[ZUSTAND_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PERSONEN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PERSONEN]  WITH CHECK ADD FOREIGN KEY([ZUSTAND_ID])
REFERENCES [dbo].[ZUSTAND] ([ZUSTAND_ID])
GO



USE datenbank
GO

/****** Object:  Table [dbo].[GRUPPE]    Script Date: 05.12.2025 13:21:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GRUPPE](
	[GRUPPE_ID] [int] NOT NULL,
	[BESCHREIBUNG] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[GRUPPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


GO

/****** Object:  Table [dbo].[GEGENSTAENDE]    Script Date: 05.12.2025 13:22:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GEGENSTAENDE](
	[GEGENSTAENDE_ID] [int] IDENTITY(1,1) NOT NULL,
	[BEZEICHNUNG] [varchar](255) NULL,
	[SERIENNUMMER] [varchar](255) NULL,
	[ABTEILUNG_ID] [int] NULL,
	[GRUPPE_ID] [int] NULL,
	[STANDORT_ID] [int] NULL,
	[WERT_ANSCHAFFUNG] [float] NULL,
	[WERT_AKTUELL] [float] NULL,
	[ANGESCHAFFT_AM] [date] NULL,
	[NOTIZ] [varchar](255) NULL,
	[ZUSTAND_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[GEGENSTAENDE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GEGENSTAENDE]  WITH CHECK ADD FOREIGN KEY([ABTEILUNG_ID])
REFERENCES [dbo].[ABTEILUNG_ABT] ([ABTEILUNG_ID])
GO

ALTER TABLE [dbo].[GEGENSTAENDE]  WITH CHECK ADD FOREIGN KEY([GRUPPE_ID])
REFERENCES [dbo].[GRUPPE] ([GRUPPE_ID])
GO

ALTER TABLE [dbo].[GEGENSTAENDE]  WITH CHECK ADD FOREIGN KEY([STANDORT_ID])
REFERENCES [dbo].[STANDORT] ([STANDORT_ID])
GO

ALTER TABLE [dbo].[GEGENSTAENDE]  WITH CHECK ADD FOREIGN KEY([ZUSTAND_ID])
REFERENCES [dbo].[ZUSTAND] ([ZUSTAND_ID])
GO

GO

/****** Object:  Table [dbo].[GEGENSTAENDE_HIST]    Script Date: 05.12.2025 13:22:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GEGENSTAENDE_HIST](
	[GEGENSTAENDE_HIST_ID] [int] IDENTITY(1,1) NOT NULL,
	[GEGENSTAENDE_ID] [int] NULL,
	[BESCHREIBUNG] [varchar](255) NULL,
	[WERT_ANSCHAFFUNG] [float] NULL,
	[WERT_AKTUELL] [float] NULL,
	[ANGELEGT_AM] [date] NULL,
	[GEAENDERT_AM] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[GEGENSTAENDE_HIST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GEGENSTAENDE_HIST]  WITH CHECK ADD FOREIGN KEY([GEGENSTAENDE_ID])
REFERENCES [dbo].[GEGENSTAENDE] ([GEGENSTAENDE_ID])
GO


GO

/****** Object:  Table [dbo].[BEREICH]    Script Date: 05.12.2025 13:23:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BEREICH](
	[BEREICH_ID] [int] NOT NULL,
	[BESCHREIBUNG] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[BEREICH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


GO

/****** Object:  Table [dbo].[ABTEILUNG_ABT]    Script Date: 05.12.2025 13:24:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ABTEILUNG_ABT](
	[ABTEILUNG_ID] [int] NOT NULL,
	[BESCHREIBUNG] [varchar](255) NULL,
	[ANGELEGT_AM] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[ABTEILUNG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
